### ISSUE TITLE
Config Help

### ISSUE THREAD

**Issue by abostriquio** [mickaelmonsieur/openob-gui#5]
Good afternoon .. I tried this web interface, but I have a small problem.

no option from the system configuration tab is working. Should I enable something?

the / etc / sudoers file with
pi ALL = (ALL) NOPASSWD: / sbin / shutdown

do not reboot working.
ips do not save and do not apply.

thanks for listening
sorry for my English..

**Comment by mickaelmonsieur** [comment]
# ⚠️ This project is no longer maintained

**openob-gui is an old Debian 8 / Raspbian Jessie project and is no longer maintained.**

If you are looking for a modern Raspberry Pi IP audio codec for broadcast use, please use **OpenSonix** instead:

# 👉 [OpenSonix — open-source Raspberry Pi IP audio codec](https://github.com/mickaelmonsieur/OpenSonix)

OpenSonix is the successor project: Raspberry Pi OS Bookworm, SIP/OPUS, web UI, real-time VU meters, Sender/Receiver modes, network configuration, diagnostics and image-based releases.

---

Mickael
